name: Pull and Merge from BoostUtils

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:


jobs:
  pull_and_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Git config
        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"

      - name: Authenticate with PAT
        run: |
          git remote set-url origin https://${{ secrets.ACTIONS_PAT }}@github.com/Manuel-Materazzo/Blood-Glucose-Prediction.git
          git fetch origin

      - name: Pull changes from BoostUtils
        run: |
          git remote add boost-utils https://github.com/Manuel-Materazzo/BoostUtils.git
          git fetch boost-utils
          git config pull.rebase false
          git pull boost-utils master --allow-unrelated-histories

      - name: Merge changes
        id: merge
        run: |
          git merge boost-utils/main --allow-unrelated-histories || echo "Merge failed" >> $GITHUB_ENV
          git push origin HEAD:main || echo "Push failed" >> $GITHUB_ENV

      - name: Install GitHub CLI
        if: env.MERGE_FAILED || env.PUSH_FAILED
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh

      - name: Create Pull Request
        if: env.MERGE_FAILED || env.PUSH_FAILED
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
        run: |
          gh auth login --with-token <<<"${{ secrets.ACTIONS_PAT }}"
          git checkout -b conflict-resolution
          git add .
          git commit -m "Resolve merge conflicts"
          git push origin conflict-resolution
          gh pr create --title "Resolve merge conflicts" --body "This PR resolves merge conflicts that occurred during the sync." --head conflict-resolution --base main