name: Pull and Merge from BoostUtils

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  pull_and_merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Git config
        run: |
          git config --global user.name "${{ secrets.GIT_USER_NAME }}"
          git config --global user.email "${{ secrets.GIT_USER_EMAIL }}"

      - name: Authenticate with PAT
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          git remote set-url origin https://${{ secrets.ACTIONS_PAT }}@github.com/Manuel-Materazzo/BoostUtils.git

      - name: Pull changes from BoostUtils
        run: |
          git remote add boost-utils https://github.com/Manuel-Materazzo/BoostUtils.git
          git fetch boost-utils
          git config pull.rebase false
          git pull boost-utils master --allow-unrelated-histories

      - name: Handle conflicts and create PR if needed
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
        run: |
          git branch -D conflict-resolution || true
          git checkout -b conflict-resolution
          git add .
          git commit -m "Resolve merge conflicts" || true
          git push -u origin conflict-resolution
          gh auth login --with-token <<<"${{ secrets.ACTIONS_PAT }}"
          gh pr create --title "Resolve merge conflicts" --body "This PR resolves merge conflicts that occurred during the sync." --head conflict-resolution --base master
